import {
  Sun,
  Moon,
  Sunrise,
  Star,
  Briefcase,
  Home,
  Target,
  Dumbbell,
  BookOpen,
  Palette,
  PersonStanding,
  Droplets,
  Coffee,
  Utensils,
  Bed,
  Timer,
  Heart,
  Brain,
  Footprints,
  Bike,
  Lightbulb,
  Droplet,
  TrendingUp,
  type LucideIcon,
} from "lucide-react";

export const DIVIDER_ICONS: { name: string; icon: LucideIcon; label: string }[] = [
  { name: "Sun", icon: Sun, label: "Morning" },
  { name: "Moon", icon: Moon, label: "Night" },
  { name: "Sunrise", icon: Sunrise, label: "Dawn" },
  { name: "Star", icon: Star, label: "Priority" },
  { name: "Briefcase", icon: Briefcase, label: "Work" },
  { name: "Home", icon: Home, label: "Home" },
  { name: "Target", icon: Target, label: "Goals" },
  { name: "Dumbbell", icon: Dumbbell, label: "Fitness" },
  { name: "BookOpen", icon: BookOpen, label: "Study" },
  { name: "Palette", icon: Palette, label: "Creative" },
];

export const TODO_ICONS: { name: string; icon: LucideIcon; label: string }[] = [
  { name: "PersonStanding", icon: PersonStanding, label: "Meditation" },
  { name: "Dumbbell", icon: Dumbbell, label: "Exercise" },
  { name: "BookOpen", icon: BookOpen, label: "Reading" },
  { name: "Droplets", icon: Droplets, label: "Hydration" },
  { name: "Coffee", icon: Coffee, label: "Morning" },
  { name: "Utensils", icon: Utensils, label: "Eating" },
  { name: "Bed", icon: Bed, label: "Sleep" },
  { name: "Timer", icon: Timer, label: "Focus" },
  { name: "Heart", icon: Heart, label: "Health" },
  { name: "Brain", icon: Brain, label: "Learning" },
  { name: "Footprints", icon: Footprints, label: "Walking" },
  { name: "Bike", icon: Bike, label: "Cycling" },
  { name: "Target", icon: Target, label: "Goals" },
  { name: "Star", icon: Star, label: "Priority" },
  { name: "Home", icon: Home, label: "Home" },
];

const iconMap: Record<string, LucideIcon> = {
  Sun,
  Moon,
  Sunrise,
  Star,
  Briefcase,
  Home,
  Target,
  Dumbbell,
  BookOpen,
  Palette,
  PersonStanding,
  Droplets,
  Droplet: Droplets,
  Coffee,
  Utensils,
  Bed,
  Timer,
  Heart,
  Brain,
  Footprints,
  Bike,
  Lightbulb,
  TrendingUp,
};

export function getIconComponent(iconName: string): LucideIcon {
  return iconMap[iconName] || Target;
}
