project_id = "toxnaophisiylhqoprsv"

[functions.ai-chat]
verify_jwt = false

[functions.physique-rater]
verify_jwt = false

[functions.outfit-rater]
verify_jwt = false

[functions.food-scanner]
verify_jwt = false

[functions.schedule-ai]
verify_jwt = false
