// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://toxnaophisiylhqoprsv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRveG5hb3BoaXNpeWxocW9wcnN2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzAzMzE1MzgsImV4cCI6MjA4NTkwNzUzOH0.OLVTkMudZD1xwxJd10Q3TiN2kEK1sslWQGOVJ5TYTS4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});